import type { Metadata } from "next";
import "./globals.css";
import { fraunces, montserrat } from "@/components/themes/primary/typography";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { ByndDigitalTheme } from "@/components/themes/bynd-digital"; // ✅ fixed path

export const metadata: Metadata = {
  title: "BYND DIGITAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${montserrat.variable}`}>
      <body>
        <ThemeProvider theme={ByndDigitalTheme}>
          <CssBaseline /> {/* ✅ resets MUI default styles */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
