import type { Metadata } from "next";
import "./globals.css";
import { fraunces, montserrat } from "@/components/themes/typography";
import { CssBaseline } from "@mui/material";
export const metadata: Metadata = {
  title: "BYND DIGITAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     <html lang="en" className={`${fraunces.variable} ${montserrat.variable}`}>
      <body>{children}</body>
    </html>
  );
}
